import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import LenisProvider from "./providers/LenisProvider";
import CallToAction from "./sessions/CallToAction";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MASZ AFRICA",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', // note the leading slash
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <LenisProvider>{children}</LenisProvider>
         <CallToAction/>
      <Footer/>
      </body>
    </html>
  );
}
